### ISSUE TITLE
Create a layout without the sidebar

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val-lang.github.io#14]
The sidebar is nice for the home page, but needlessly eats space for the language tour. It would be best to have a layout that uses the full width of the page. Perhaps it would also address #9

**Comment by dabrahams** [comment]
Eh, disagreed; full-width is almost always too wide, especially these days when monitors become increasingly horizontal.  It hurts readability by making it hard to find the beginning of the next line when you finish the last one. Also full width conflicts with the desire we just discussed to add SwiftRef-like navigation.

**Comment by kyouko-taiga** [comment]
Sounds reasonable.
