### ISSUE TITLE
Typo in sample code

### ISSUE THREAD

**Issue by rayx** [val-lang/val-lang.github.io#26]
"&" is missing in the sample code in binding lifetime section.

    public fun main() {
      let weight = 1.0
      let base_length = 2.0
      var length = base_length 
      length += 3.0            
      // Q: shouldn't it be "&length += 3.0"?
      ...
    }

**Comment by kyouko-taiga** [comment]
Good catch, thanks. It's been corrected.
FYI, the tour is now a git book: https://tour.val-lang.dev/
